[tool.poetry]
name = "poetry"
version = "0.1.0"
description = ""
authors = ["Eric Kincl <eric@kincl.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
pytest = "^8.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
